[package]
name = "neural01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rayon = "1.10.0"
rustacuda = "0.1.3"
rustacuda_derive = "0.1"
rustacuda_core = "0.1"
itertools = "0.12.1"
