[package]
name = "neural01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rayon = "1.10.0"
itertools = "0.12.1"
cudarc = "0.10.0"

[env]
RUST_BACKTRACE=1
CUDA_LAUNCH_BLOCKING=1
